[package]
name = "attribute"
version = "0.1.0"
authors = ["Azriel Hoh <azriel91@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version =  "0.15.29", features = ["extra-traits", "full"] }
proc-macro2 = "0.4.27"
quote = "0.6.11"
